### PR TITLE
Add Override path method

### PR DESCRIPTION
**Pull request by eseQ**
Hello.
That method can help use overrides not only from parent folder.
I wrote it for my project and may be that will be useful.

### CODE REVIEW

**Comment by rosskevin** [comment]
Hey thanks for the PR!

I'm not opposed to accepting this, but I don't understand the use case (and that means neither will users). I'd like a couple of changes before we merge:
- test for it to prove `replace` works
- better description of the use case for the readme

I think it is important that we can clearly articulate the use case for the option, otherwise it just adds code here and is only used by you.  I'd like to make sure your work can be shared with others.  I can help with the english if you can communicate the fundamental use case.

**Comment by eseQ** [comment]
@rosskevin thanks for answer.  With only `path.join` all path will be by `locales` folder.
For example. User has 2 folders:
1) With main app: `~/apps/myApp/client/locales`;
2) With local package: `~/packages/myPackage/locales`;
In this case we need a way to use absolute path.

`join | resolve` is sufficient for this case. I can remove `replace`.
Can u help me with readme? Thank you.

**Comment by rosskevin** [comment]
I can help with the readme, I just need you to write a realistic test case to demonstrate/assert the correct output.

**Comment by rosskevin** [comment]
I'm going to close this since there has been no follow up.  If you want to pursue this and create the test case, I am happy to reopen.

**Pull request closed without merging**
